#!/usr/bin/env python3
"""
Production Setup Script for CaseCite

This script helps generate and rotate production secrets securely.
Run this script to:
1. Generate new cryptographic secrets
2. Create a .env file template with secure values
3. Validate existing configuration

Usage:
    python scripts/setup_production.py --generate-secrets
    python scripts/setup_production.py --validate
    python scripts/setup_production.py --rotate-secret-key
"""

import argparse
import secrets
import sys
from pathlib import Path


def generate_secret_key() -> str:
    """Generate a cryptographically secure secret key (64 hex chars = 32 bytes)."""
    return secrets.token_hex(32)


def generate_encryption_salt() -> str:
    """Generate a cryptographically secure encryption salt (32 hex chars = 16 bytes)."""
    return secrets.token_hex(16)


def generate_api_key_placeholder() -> str:
    """Generate a placeholder for API keys."""
    return f"REPLACE_ME_{secrets.token_hex(8).upper()}"


def print_secrets():
    """Generate and print new secrets."""
    print("\n" + "=" * 60)
    print("GENERATED PRODUCTION SECRETS")
    print("=" * 60)
    print("\nCopy these values to your .env file or secrets manager:\n")
    print(f"SECRET_KEY={generate_secret_key()}")
    print(f"ENCRYPTION_SALT={generate_encryption_salt()}")
    print("\n" + "=" * 60)
    print("IMPORTANT SECURITY NOTES:")
    print("=" * 60)
    print("1. Never commit these values to git")
    print("2. Use a secrets manager in production (AWS Secrets Manager, Azure Key Vault)")
    print("3. Rotate encryption keys: python scripts/rotate_encryption_key.py")
    print("4. Keep backups of secrets in a secure location")
    print("=" * 60 + "\n")


def create_env_template():
    """Create a new .env template with generated secrets."""
    env_content = f"""# CaseCite RAG Platform - Production Configuration
# ==================================================
# Generated by setup_production.py
# IMPORTANT: This file contains sensitive credentials. Never commit to git.

# ============================================
# REQUIRED: AI Provider Keys
# ============================================
# Get at https://platform.openai.com/api-keys
OPENAI_API_KEY={generate_api_key_placeholder()}

# Optional: Better legal embeddings (highly recommended)
# Get from https://www.voyageai.com/
VOYAGE_API_KEY=

# Optional: Alternative LLM (Claude)
# Get from https://console.anthropic.com/
ANTHROPIC_API_KEY=

# ============================================
# REQUIRED: Security Secrets
# ============================================
# These were auto-generated. Store backup securely!
# WARNING: never change ENCRYPTION_SALT or SECRET_KEY after first run — at-rest
# encrypted data (API keys, connector tokens) becomes unrecoverable.
SECRET_KEY={generate_secret_key()}
ENCRYPTION_SALT={generate_encryption_salt()}
AUDIT_HMAC_KEY={generate_secret_key()}
# Previous encryption salts for key rotation (comma-separated, oldest last)
# See: python scripts/rotate_encryption_key.py
ENCRYPTION_SALT_PREVIOUS=

# ============================================
# REQUIRED: Database & Redis
# ============================================
# The bundled docker-compose.prod.yml interpolates these passwords AND builds
# DATABASE_URL/REDIS_URL from them, so set the passwords below. If you point at
# an EXTERNAL managed database, set DATABASE_URL/REDIS_URL directly instead and
# set DB_SSL=require.
POSTGRES_PASSWORD={generate_secret_key()}
REDIS_PASSWORD={generate_secret_key()}
# DATABASE_URL=postgresql+asyncpg://user:password@host:5432/casecite
# REDIS_URL=redis://:password@host:6379/0

# ============================================
# Environment Settings
# ============================================
ENVIRONMENT=production
DEBUG=false

# ============================================
# REQUIRED: Domain, CORS, Allowed Hosts
# ============================================
# DOMAIN drives the bundled Caddy proxy; CORS_ORIGINS/ALLOWED_HOSTS default from it.
DOMAIN=your-domain.com
CORS_ORIGINS=https://your-domain.com
ALLOWED_HOSTS=your-domain.com
# Behind an external reverse proxy, set this to the proxy's IP/subnet or all
# clients collapse to one IP (rate limits + lockout break). See docs.
# TRUSTED_PROXIES=10.0.0.0/8,172.16.0.0/12

# ============================================
# Legal Tools Integration
# ============================================
# FREE - Get token at https://www.courtlistener.com/profile/
COURTLISTENER_API_TOKEN=

# ============================================
# OAuth Redirect URIs (set for production domain)
# ============================================
# Replace yourdomain.com with your actual domain
GOOGLE_REDIRECT_URI=https://api.yourdomain.com/api/v1/connectors/google/callback
MICROSOFT_REDIRECT_URI=https://api.yourdomain.com/api/v1/connectors/microsoft/callback
BOX_REDIRECT_URI=https://api.yourdomain.com/api/v1/connectors/box/callback
DROPBOX_REDIRECT_URI=https://api.yourdomain.com/api/v1/connectors/dropbox/callback
NETDOCUMENTS_REDIRECT_URI=https://api.yourdomain.com/api/v1/connectors/netdocuments/callback
IMANAGE_REDIRECT_URI=https://api.yourdomain.com/api/v1/connectors/imanage/callback
CLIO_REDIRECT_URI=https://api.yourdomain.com/api/v1/integrations/clio/callback

# ============================================
# OAuth Credentials (get from respective providers)
# ============================================
# Google - https://console.cloud.google.com/
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_API_KEY=
GOOGLE_APP_ID=

# Microsoft - https://portal.azure.com/
MICROSOFT_CLIENT_ID=
MICROSOFT_CLIENT_SECRET=
MICROSOFT_TENANT_ID=

# Box - https://developer.box.com/
BOX_CLIENT_ID=
BOX_CLIENT_SECRET=

# Dropbox - https://www.dropbox.com/developers/
DROPBOX_APP_KEY=
DROPBOX_APP_SECRET=

# ============================================
# Email (SendGrid) — optional
# ============================================
# Enables password-reset emails. Self-service change-password works without it.
# Get from https://sendgrid.com/
SENDGRID_API_KEY=
"""
    return env_content


def validate_env_file(env_path: Path) -> bool:
    """Validate that the .env file has required production settings."""
    if not env_path.exists():
        print(f"ERROR: .env file not found at {env_path}")
        return False

    with open(env_path) as f:
        content = f.read()

    required_vars = [
        "SECRET_KEY",
        "ENCRYPTION_SALT",
        "DATABASE_URL",
        "REDIS_URL",
        "OPENAI_API_KEY",
        "CORS_ORIGINS",
    ]

    issues = []
    warnings = []

    for var in required_vars:
        if f"{var}=" not in content:
            issues.append(f"Missing required variable: {var}")
        else:
            # Check for placeholder values
            for line in content.split("\n"):
                if line.startswith(f"{var}="):
                    value = line.split("=", 1)[1].strip()
                    if not value or value.startswith("REPLACE") or value == "your-key-here":
                        issues.append(f"{var} has placeholder value - needs real value")
                    elif var == "SECRET_KEY" and len(value) < 32:
                        issues.append(f"{var} is too short - needs 32+ characters")

    # Check for debug mode
    for line in content.split("\n"):
        if line.startswith("DEBUG=true") or line.startswith("DEBUG=True"):
            warnings.append("DEBUG is enabled - should be false for production")

    # Print results
    print("\n" + "=" * 60)
    print("ENVIRONMENT VALIDATION RESULTS")
    print("=" * 60)

    if issues:
        print("\n❌ ISSUES FOUND (must fix):")
        for issue in issues:
            print(f"   - {issue}")

    if warnings:
        print("\n⚠️  WARNINGS:")
        for warning in warnings:
            print(f"   - {warning}")

    if not issues and not warnings:
        print("\n✅ All validation checks passed!")

    print("=" * 60 + "\n")

    return len(issues) == 0


def main():
    parser = argparse.ArgumentParser(description="Production setup and secret management for CaseCite")
    parser.add_argument(
        "--generate-secrets",
        action="store_true",
        help="Generate new cryptographic secrets",
    )
    parser.add_argument(
        "--create-env",
        action="store_true",
        help="Create a new .env.production template file",
    )
    parser.add_argument(
        "--validate", action="store_true", help="Validate existing .env configuration"
    )
    parser.add_argument(
        "--env-file", type=str, default=".env", help="Path to .env file (default: .env)"
    )

    args = parser.parse_args()

    if not any([args.generate_secrets, args.create_env, args.validate]):
        parser.print_help()
        print("\nExamples:")
        print("  python scripts/setup_production.py --generate-secrets")
        print("  python scripts/setup_production.py --create-env")
        print("  python scripts/setup_production.py --validate")
        sys.exit(1)

    if args.generate_secrets:
        print_secrets()

    if args.create_env:
        output_path = Path(args.env_file + ".production")
        env_content = create_env_template()
        with open(output_path, "w") as f:
            f.write(env_content)
        print(f"\n✅ Created {output_path}")
        print("   Review and rename to .env for production use")
        print("   IMPORTANT: Keep a secure backup of the generated secrets!\n")

    if args.validate:
        # Find project root
        script_dir = Path(__file__).parent
        project_root = script_dir.parent
        env_path = project_root / args.env_file
        success = validate_env_file(env_path)
        sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
