#!/usr/bin/env python3
"""
Production Setup Script for CaseCite

This script helps generate production secrets securely.
Run this script to:
1. Generate new cryptographic secrets
2. Create a .env file with secure values
3. Validate existing configuration

Usage:
    python3 scripts/setup_production.py --generate-secrets
    python3 scripts/setup_production.py --create-env --domain app.example.com
    python3 scripts/setup_production.py --validate

Rotating ENCRYPTION_SALT is a separate tool (scripts/rotate_encryption_key.py);
SECRET_KEY cannot be rotated in place — see docs/secret-rotation.md.
"""

import argparse
import os
import secrets
import sys
from pathlib import Path

# Mirrors _PLACEHOLDER_PREFIXES in backend/app/config.py, plus the values this
# script and .env.example use for "fill this in".
PLACEHOLDER_PREFIXES = ("change-me", "REPLACE_WITH", "REPLACE-ME", "your-", "sk-your")
PLACEHOLDER_DOMAIN = "your-domain.com"


def generate_secret_key() -> str:
    """Generate a cryptographically secure secret key (64 hex chars = 32 bytes)."""
    return secrets.token_hex(32)


def generate_encryption_salt() -> str:
    """Generate a cryptographically secure encryption salt (32 hex chars = 16 bytes)."""
    return secrets.token_hex(16)


def print_secrets():
    """Generate and print new secrets."""
    print("\n" + "=" * 60)
    print("GENERATED PRODUCTION SECRETS")
    print("=" * 60)
    print("\nCopy these values to your .env file or secrets manager:\n")
    print(f"SECRET_KEY={generate_secret_key()}")
    print(f"ENCRYPTION_SALT={generate_encryption_salt()}")
    print(f"AUDIT_HMAC_KEY={generate_secret_key()}")
    print(f"POSTGRES_PASSWORD={generate_secret_key()}")
    print(f"REDIS_PASSWORD={generate_secret_key()}")
    print("\n" + "=" * 60)
    print("IMPORTANT SECURITY NOTES:")
    print("=" * 60)
    print("1. Never commit these values to git")
    print("2. Use a secrets manager in production (AWS Secrets Manager, Azure Key Vault)")
    print("3. Never change SECRET_KEY or ENCRYPTION_SALT after first run without")
    print("   following docs/secret-rotation.md — encrypted data becomes unreadable")
    print("4. Keep a copy of SECRET_KEY, ENCRYPTION_SALT and AUDIT_HMAC_KEY off the")
    print("   server: backups cannot be restored without them")
    print("=" * 60 + "\n")


def create_env_template(domain: str = PLACEHOLDER_DOMAIN, disk_encrypted: bool = False) -> str:
    """Create a new .env with generated secrets."""
    env_content = f"""# CaseCite - Production Configuration
# ==================================================
# Generated by setup_production.py
# IMPORTANT: This file contains sensitive credentials. Never commit to git.

# ============================================
# AI Provider Keys (optional at the server level)
# ============================================
# Leave all of these empty for a bring-your-own-key instance: each user then
# saves their own provider key under Settings. Set one here to give every user
# a shared server-level key.
# Get at https://platform.openai.com/api-keys
OPENAI_API_KEY=

# Optional: legal-tuned embeddings. Get from https://www.voyageai.com/
VOYAGE_API_KEY=

# Optional: Alternative LLM (Claude). Get from https://console.anthropic.com/
ANTHROPIC_API_KEY=

# ============================================
# REQUIRED: Security Secrets
# ============================================
# These were auto-generated. Keep a copy OFF this server: a backup cannot be
# restored without SECRET_KEY, ENCRYPTION_SALT and AUDIT_HMAC_KEY.
# WARNING: never change ENCRYPTION_SALT or SECRET_KEY after first run — at-rest
# encrypted data (documents, API keys, connector tokens) becomes unrecoverable.
SECRET_KEY={generate_secret_key()}
ENCRYPTION_SALT={generate_encryption_salt()}
AUDIT_HMAC_KEY={generate_secret_key()}
# Previous encryption salts for key rotation (comma-separated, oldest last)
# See: python3 scripts/rotate_encryption_key.py
ENCRYPTION_SALT_PREVIOUS=

# ============================================
# REQUIRED: Database & Redis
# ============================================
# The bundled docker-compose.prod.yml interpolates these passwords AND builds
# DATABASE_URL/REDIS_URL from them, so set the passwords below. If you point at
# an EXTERNAL managed database, set DATABASE_URL/REDIS_URL directly instead and
# set DB_SSL=require.
POSTGRES_PASSWORD={generate_secret_key()}
REDIS_PASSWORD={generate_secret_key()}
# DATABASE_URL=postgresql+asyncpg://user:password@host:5432/casecite
# REDIS_URL=redis://:password@host:6379/0

# ============================================
# REQUIRED: Data-at-rest acknowledgement
# ============================================
# Vector chunks, chat history and extracted clause text are stored in
# cleartext. Put the Docker volumes (rag_data, postgres_data, redis_data) on an
# encrypted disk (LUKS or provider disk encryption), then set this to true.
# Production refuses to start until it is.
DISK_ENCRYPTION_ACKNOWLEDGED={"true" if disk_encrypted else "false"}

# ============================================
# Environment Settings
# ============================================
DEBUG=false

# ============================================
# REQUIRED: Domain, CORS, Allowed Hosts
# ============================================
# DOMAIN drives the bundled Caddy proxy; CORS_ORIGINS/ALLOWED_HOSTS default from it.
DOMAIN={domain}
CORS_ORIGINS=https://{domain}
ALLOWED_HOSTS={domain}
FRONTEND_URL=https://{domain}
# Behind an external reverse proxy, set this to the proxy's IP/subnet or all
# clients collapse to one IP (rate limits + lockout break). See docs.
# TRUSTED_PROXIES=10.0.0.0/8,172.16.0.0/12

# ============================================
# First-admin bootstrap
# ============================================
# REQUIRED in production: the FIRST account (the admin) can only be registered
# by someone who supplies this token, so nobody else who reaches a fresh
# instance can claim the admin slot. See "Create the admin account" in
# docs/deployment.md.
REGISTRATION_BOOTSTRAP_TOKEN={secrets.token_urlsafe(24)}

# ============================================
# Legal Tools Integration
# ============================================
# FREE - Get token at https://www.courtlistener.com/profile/
COURTLISTENER_API_TOKEN=

# ============================================
# OAuth Redirect URIs
# ============================================
# The API is served from the same hostname as the app, under /api/v1.
GOOGLE_REDIRECT_URI=https://{domain}/api/v1/connectors/google/callback
MICROSOFT_REDIRECT_URI=https://{domain}/api/v1/connectors/microsoft/callback
BOX_REDIRECT_URI=https://{domain}/api/v1/connectors/box/callback
DROPBOX_REDIRECT_URI=https://{domain}/api/v1/connectors/dropbox/callback
NETDOCUMENTS_REDIRECT_URI=https://{domain}/api/v1/connectors/netdocuments/callback
IMANAGE_REDIRECT_URI=https://{domain}/api/v1/connectors/imanage/callback
CLIO_REDIRECT_URI=https://{domain}/api/v1/connectors/clio/callback

# ============================================
# OAuth Credentials (get from respective providers)
# ============================================
# Google - https://console.cloud.google.com/
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_API_KEY=
GOOGLE_APP_ID=

# Microsoft - https://portal.azure.com/
MICROSOFT_CLIENT_ID=
MICROSOFT_CLIENT_SECRET=
MICROSOFT_TENANT_ID=

# Box - https://developer.box.com/
BOX_CLIENT_ID=
BOX_CLIENT_SECRET=

# Dropbox - https://www.dropbox.com/developers/
DROPBOX_APP_KEY=
DROPBOX_APP_SECRET=

# ============================================
# Email (SendGrid) — optional
# ============================================
# Enables password-reset emails. Self-service change-password works without it.
# Get from https://sendgrid.com/
SENDGRID_API_KEY=
"""
    return env_content


def _parse_env(content: str) -> dict[str, str]:
    """Parse KEY=value lines (comments and blanks skipped; last assignment wins)."""
    values: dict[str, str] = {}
    for raw in content.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def _is_placeholder(value: str) -> bool:
    return (
        not value
        or value.startswith(PLACEHOLDER_PREFIXES)
        or value.startswith("REPLACE")
        or PLACEHOLDER_DOMAIN in value
    )


def validate_env_file(env_path: Path) -> bool:
    """Validate that the .env file has required production settings."""
    if not env_path.exists():
        print(f"ERROR: .env file not found at {env_path}")
        return False

    with open(env_path, encoding="utf-8") as f:
        values = _parse_env(f.read())

    issues = []
    warnings = []

    # Always required. The app refuses to start in production without these.
    for var in ("SECRET_KEY", "ENCRYPTION_SALT", "AUDIT_HMAC_KEY"):
        value = values.get(var, "")
        if var not in values:
            issues.append(f"Missing required variable: {var}")
        elif _is_placeholder(value):
            issues.append(f"{var} has placeholder value - needs real value")
        elif var != "ENCRYPTION_SALT" and len(value) < 32:
            issues.append(f"{var} is too short - needs 32+ characters")

    # Database / Redis: either the URL itself, or the password the bundled
    # docker-compose.prod.yml builds the URL from.
    for url_var, password_var in (
        ("DATABASE_URL", "POSTGRES_PASSWORD"),
        ("REDIS_URL", "REDIS_PASSWORD"),
    ):
        url, password = values.get(url_var, ""), values.get(password_var, "")
        if _is_placeholder(url) and _is_placeholder(password):
            issues.append(
                f"Set {password_var} (bundled docker-compose.prod.yml) or {url_var} "
                "(external service)"
            )

    # Hostname: DOMAIN (bundled stack derives CORS_ORIGINS/ALLOWED_HOSTS from it)
    # or both set explicitly (docker-compose.yml / bare metal).
    domain = values.get("DOMAIN", "")
    if _is_placeholder(domain):
        for var in ("CORS_ORIGINS", "ALLOWED_HOSTS"):
            if _is_placeholder(values.get(var, "")):
                issues.append(f"{var} is not set (or set DOMAIN for the bundled stack)")
    for var in ("DOMAIN", "CORS_ORIGINS", "ALLOWED_HOSTS", "FRONTEND_URL"):
        if PLACEHOLDER_DOMAIN in values.get(var, ""):
            issues.append(f"{var} still contains the placeholder '{PLACEHOLDER_DOMAIN}'")

    if values.get("DISK_ENCRYPTION_ACKNOWLEDGED", "").lower() != "true":
        issues.append(
            "DISK_ENCRYPTION_ACKNOWLEDGED is not true - encrypt the data volumes, "
            "then set it to true (the app refuses to start otherwise)"
        )

    if values.get("DEBUG", "").lower() == "true":
        issues.append("DEBUG is enabled - must be false for production")

    # Advisory only: a server-level provider key is optional (BYOK).
    if all(_is_placeholder(values.get(var, "")) for var in ("OPENAI_API_KEY", "ANTHROPIC_API_KEY")):
        warnings.append(
            "No server-level AI provider key - fine for bring-your-own-key, but each "
            "user must save their own key under Settings before anything works"
        )
    for var in ("OPENAI_API_KEY", "ANTHROPIC_API_KEY", "VOYAGE_API_KEY", "COHERE_API_KEY"):
        value = values.get(var, "")
        if value and _is_placeholder(value):
            issues.append(f"{var} has placeholder value - set a real key or leave it empty")
    if not values.get("REGISTRATION_BOOTSTRAP_TOKEN"):
        warnings.append(
            "REGISTRATION_BOOTSTRAP_TOKEN is not set - on a fresh instance the first "
            "(admin) account cannot be registered without it"
        )
    if values.get("BACKUP_ENCRYPTION_KEY"):
        warnings.append(
            "BACKUP_ENCRYPTION_KEY is in this file - keep it off this server (supply "
            "it in the backup job's environment instead)"
        )

    # Print results
    print("\n" + "=" * 60)
    print("ENVIRONMENT VALIDATION RESULTS")
    print("=" * 60)

    if issues:
        print("\n[FAIL] ISSUES FOUND (must fix):")
        for issue in issues:
            print(f"   - {issue}")

    if warnings:
        print("\n[WARN] WARNINGS:")
        for warning in warnings:
            print(f"   - {warning}")

    if not issues and not warnings:
        print("\n[OK] All validation checks passed!")
    elif not issues:
        print("\n[OK] No blocking issues.")

    print("=" * 60 + "\n")

    return len(issues) == 0


def main():
    parser = argparse.ArgumentParser(
        description="Production setup and secret generation for CaseCite"
    )
    parser.add_argument(
        "--generate-secrets",
        action="store_true",
        help="Generate new cryptographic secrets",
    )
    parser.add_argument(
        "--create-env",
        action="store_true",
        help="Create the .env file (refuses to overwrite an existing one)",
    )
    parser.add_argument(
        "--domain",
        type=str,
        default=PLACEHOLDER_DOMAIN,
        help="With --create-env: the public hostname (e.g. app.example.com)",
    )
    parser.add_argument(
        "--disk-encrypted",
        action="store_true",
        help="With --create-env: set DISK_ENCRYPTION_ACKNOWLEDGED=true "
        "(only if the data volumes are on an encrypted disk)",
    )
    parser.add_argument(
        "--validate", action="store_true", help="Validate existing .env configuration"
    )
    parser.add_argument(
        "--env-file",
        type=str,
        default=".env",
        help="Path to the .env file, relative to the repository root (default: .env)",
    )

    args = parser.parse_args()

    if not any([args.generate_secrets, args.create_env, args.validate]):
        parser.print_help()
        print("\nExamples:")
        print("  python3 scripts/setup_production.py --generate-secrets")
        print("  python3 scripts/setup_production.py --create-env --domain app.example.com")
        print("  python3 scripts/setup_production.py --validate")
        sys.exit(1)

    project_root = Path(__file__).resolve().parent.parent
    env_path = Path(args.env_file)
    if not env_path.is_absolute():
        env_path = project_root / env_path

    if args.generate_secrets:
        print_secrets()

    if args.create_env:
        if env_path.exists():
            print(f"ERROR: {env_path} already exists - refusing to overwrite it.")
            print("       Its SECRET_KEY/ENCRYPTION_SALT may protect existing data.")
            print("       Pass --env-file <other-name> to write somewhere else.")
            sys.exit(1)
        env_content = create_env_template(args.domain, args.disk_encrypted)
        # Owner read/write only from the moment the file exists (no-op on Windows).
        fd = os.open(env_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(env_content)
        print(f"\n[OK] Created {env_path} (mode 0600)")
        if args.domain == PLACEHOLDER_DOMAIN:
            print(f"   Replace '{PLACEHOLDER_DOMAIN}' with your hostname")
        if not args.disk_encrypted:
            print("   Set DISK_ENCRYPTION_ACKNOWLEDGED=true once the volumes are encrypted")
        print("   Then run: python3 scripts/setup_production.py --validate")
        print("   IMPORTANT: Keep a secure backup of the generated secrets!\n")

    if args.validate:
        success = validate_env_file(env_path)
        sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
